### ISSUE TITLE
Address Excessive 502 Errors

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-proxy#8]
We receive an inordinate number of 502 errors when posting messages from the ESB via the Knack proxy. We receive 502s on more than half of ESB-triggered posts, vs very few for our other scripts. The working theory is that this error is limited to `POST` requests, and the ESB makes many at once. The issue is compounded by the fact that, when a request fails, it is returned to the ESB queue. When the ESB attempts to send messages 5 min later, the queue is even longer than it was before, thus increasing the likelihood of overloading Knack's server.

We do see the issue in our other scripts which `POST` to Knack (e.g., `sr_asset_assign.py`), so the long term solution (besides Knack fixing their infrastructure), is to build throttling into knackpy. We're going to start by adding throttling to the knack-proxy, and see if that fixes the problem.

**Comment by johnclary** [comment]
The development branch has been deployed in production for testing.

**Comment by amenity** [comment]
@johnclary  - It looks like this took place in Sprint 9, so sticking that milestone on it. Plz label and estimate. ;)

**Comment by johnclary** [comment]
The issue persists. we got sidelined with the DNS issues. now need to hold until we migrated `transportation-data` to new AWS org.

**Comment by johnclary** [comment]
moved to backlog and targeting sprint 11

**Comment by amenity** [comment]
@johnclary ping 🛎

**Comment by johnclary** [comment]
This has been resolved by the migration of the proxy server to AWS lambda.
